### PR TITLE
Add more language copy

### PR DESCRIPTION
**Pull request by tnylea**
This is the new PR from this original PR https://github.com/thedevdojo/auth/pull/36

@m0ham4d, here is the new PR that we'll try to merge into main.

### CODE REVIEW

**Comment by m0ham4d** [comment]
@tnylea Im ready to make more updates on this repo
let me know if everything was ok

**Comment by tnylea** [comment]
BTW, I added a quick fix to a few places. Looks like one of the configs had this in it:

```
'dont_have_an_account?' => 'Don\'t have an account?',
```

With a `?` in the key, so it wasn't working correctly. Got that updated 😉 so pull the latest on your end when you want to make additional updates 😊

**Comment by m0ham4d** [comment]
Yes, i will continue adding additional change to my PR 🙂‍↔️

**Comment by tnylea** [comment]
Perfect! If you need my help with any merge conflicts, let me know. I've released a small update since the last version 😉

**Pull request merged**
