### PR TITLE
Fix Google Login Callback Error

### LINKED ISSUE #78: Google Login Callback Error Because of the Composite Primary Keys
**Describe the bug**
The `createSocialProvider` function will return an error because Laravel doesn't support composite primary keys defined in the `SocialProviderUser` model. It's related to the [Pull Request](https://github.com/thedevdojo/auth/issues/51).

**To Reproduce**
1. Setup the Google Login Provider
2. Login to Google with an Account not registered in the database yet.
3. The error below will shown

**Expected behavior**
Login successfully without an error.

**Screenshots**
Screenshot 2024-07-03 at 06 13 01
Screenshot 2024-07-03 at 06 13 38

**System Details**
 - OS: MacOS Sonoa
 - Browser: Arc Browser (Chromium)
 - Auth Version: 1.0.3
 - Laravel Version: v11.14.0 

**Current Solution**
Simply adding [thiagoprz/eloquent-composite-key](https://github.com/thiagoprz/eloquent-composite-key) package will solve the problem.

```php
use Thiagoprz\CompositeKey\HasCompositeKey;

class SocialProviderUser extends Model
{
    use HasCompositeKey;
    protected $table = 'social_provider_user';
    // Prevents the "returning id" default behaviour
    protected $primaryKey = ['user_id', 'provider_slug'];
```

### PR DESCRIPTION
**Pull request by arbiyanto**
Resolve #78

### CODE REVIEW

**Comment by arbiyanto** [comment]
Resolve #78

**Comment by tnylea** [comment]
Thanks @arbiyanto I'll be looking into this tomorrow and testing it out on my end. Appreciate the PR 😉

**Review by tnylea — CHANGES_REQUESTED** [review]
Thanks for the PR. I'm unable to replicate this behavior and I want to make sure nothing unneccessarily gets added to this project.

Here's a quick sped up version of me walking through creating a new laravel app, installing the package, and setting up Google Authentication.


https://github.com/user-attachments/assets/953054c0-dd1a-4d68-b259-77396b90133c

Maybe there's something that you are doing on your end that I am not. Let me know if you can create a quick screenflow of the behavior you are describing.

Thanks a ton!

**Comment by tnylea** [comment]
Closing this PR for now, if you still have the issue and can replicate it for me, feel free to re-open.

Thanks!

**Pull request closed without merging**
